---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
{{- range .Values.rbac.adminGroupResouces }}
- apiGroups:
{{ .groups | toYaml | indent 4 }}
  resources:
{{ .resources | toYaml | indent 4 }}
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
- apiGroups:
  - template.onmetal.de
  resources:
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - template.onmetal.de
  resources:
  - templates/finalizers
  verbs:
  - update
- apiGroups:
  - template.onmetal.de
  resources:
  - templates/status
  verbs:
  - get
  - patch
  - update
